/***************************************************************************************************
| H | O | R | I | Z | O | N |   | L | A | B | S |

Demo:         Horizon Catalog - Idempotent Setup
Version:      HLab v2.1 (Idempotent)
Author:       Based on Snowflake-Labs quickstart v2.0 by Ravi Kumar & Severin Gassauer
Copyright(c): 2026 Snowflake Inc. All rights reserved.
***************************************************************************************************/

/*=============================================================================
  IDEMPOTENT RESET PREAMBLE
  
  This block can be run any number of times safely.
  It nukes all state and rebuilds from scratch.
  Assumes 99-teardown.sql has been run first to guarantee a clean
  account. If not, run teardown before this script.
=============================================================================*/

USE ROLE ACCOUNTADMIN;

DROP DATABASE IF EXISTS HRZN_DB;

/*=============================================================================
  ROLES (CREATE OR REPLACE is idempotent)
=============================================================================*/

USE ROLE SECURITYADMIN;

CREATE OR REPLACE ROLE HRZN_DATA_ENGINEER;
CREATE OR REPLACE ROLE HRZN_DATA_GOVERNOR;
CREATE OR REPLACE ROLE HRZN_DATA_USER;
CREATE OR REPLACE ROLE HRZN_IT_ADMIN;

GRANT ROLE HRZN_DATA_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE HRZN_DATA_GOVERNOR TO ROLE SYSADMIN;
GRANT ROLE HRZN_DATA_USER TO ROLE SYSADMIN;
GRANT ROLE HRZN_IT_ADMIN TO ROLE SYSADMIN;

BEGIN
    LET usr VARCHAR := CURRENT_USER();
    EXECUTE IMMEDIATE 'GRANT ROLE HRZN_DATA_ENGINEER TO USER identifier(?)' USING (usr);
    EXECUTE IMMEDIATE 'GRANT ROLE HRZN_DATA_GOVERNOR TO USER identifier(?)' USING (usr);
    EXECUTE IMMEDIATE 'GRANT ROLE HRZN_DATA_USER TO USER identifier(?)' USING (usr);
    EXECUTE IMMEDIATE 'GRANT ROLE HRZN_IT_ADMIN TO USER identifier(?)' USING (usr);
END;

/*=============================================================================
  WAREHOUSE (CREATE OR REPLACE is idempotent)
=============================================================================*/

USE ROLE SYSADMIN;
CREATE OR REPLACE WAREHOUSE HRZN_WH WITH WAREHOUSE_SIZE='X-SMALL';
USE WAREHOUSE HRZN_WH;
GRANT USAGE ON WAREHOUSE HRZN_WH TO ROLE HRZN_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE HRZN_WH TO ROLE HRZN_DATA_GOVERNOR;
GRANT USAGE ON WAREHOUSE HRZN_WH TO ROLE HRZN_DATA_USER;
GRANT USAGE ON WAREHOUSE HRZN_WH TO ROLE HRZN_IT_ADMIN;
GRANT MODIFY ON WAREHOUSE HRZN_WH TO ROLE HRZN_IT_ADMIN;

/*=============================================================================
  DATABASE + SCHEMAS
=============================================================================*/

GRANT CREATE DATABASE ON ACCOUNT TO ROLE HRZN_DATA_ENGINEER;

USE ROLE HRZN_DATA_ENGINEER;
CREATE OR REPLACE DATABASE HRZN_DB;
CREATE OR REPLACE SCHEMA HRZN_DB.HRZN_SCH;

GRANT USAGE ON DATABASE HRZN_DB TO ROLE HRZN_DATA_GOVERNOR;
GRANT USAGE ON SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_GOVERNOR;
GRANT CREATE SCHEMA ON DATABASE HRZN_DB TO ROLE HRZN_DATA_GOVERNOR;

GRANT USAGE ON ALL SCHEMAS IN DATABASE HRZN_DB TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE HRZN_DB TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT ON ALL TABLES IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_GOVERNOR;

GRANT USAGE ON DATABASE HRZN_DB TO ROLE HRZN_IT_ADMIN;
GRANT USAGE ON SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_IT_ADMIN;
GRANT CREATE SCHEMA ON DATABASE HRZN_DB TO ROLE HRZN_IT_ADMIN;

GRANT USAGE ON DATABASE HRZN_DB TO ROLE HRZN_DATA_USER;
GRANT USAGE ON SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_USER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE HRZN_DB TO ROLE HRZN_DATA_USER;
GRANT SELECT ON ALL TABLES IN DATABASE HRZN_DB TO ROLE HRZN_DATA_USER;

/*=============================================================================
  GOVERNOR SCHEMAS (classifiers, tags, security policies)
=============================================================================*/

USE ROLE HRZN_DATA_GOVERNOR;

CREATE OR REPLACE SCHEMA HRZN_DB.CLASSIFIERS
    COMMENT = 'Schema containing Classifiers';

CREATE OR REPLACE SCHEMA HRZN_DB.TAG_SCHEMA
    COMMENT = 'Schema containing Tags';

CREATE OR REPLACE TABLE HRZN_DB.TAG_SCHEMA.ROW_POLICY_MAP
    (role STRING, state_visibility STRING);

INSERT INTO HRZN_DB.TAG_SCHEMA.ROW_POLICY_MAP
    VALUES
    ('HRZN_DATA_USER','CA'),
    ('HRZN_DATA_USER','TX'),
    ('HRZN_DATA_USER','MA');

CREATE OR REPLACE SCHEMA HRZN_DB.SEC_POLICIES_SCHEMA
    COMMENT = 'Schema containing Security Policies';

/*=============================================================================
  FUTURE GRANTS
=============================================================================*/

USE ROLE SECURITYADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN DATABASE HRZN_DB TO ROLE HRZN_DATA_GOVERNOR;

GRANT SELECT ON FUTURE TABLES IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_USER;
GRANT SELECT ON FUTURE TABLES IN DATABASE HRZN_DB TO ROLE HRZN_DATA_USER;

GRANT SELECT ON FUTURE TABLES IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_IT_ADMIN;
GRANT SELECT ON FUTURE TABLES IN DATABASE HRZN_DB TO ROLE HRZN_IT_ADMIN;

GRANT USAGE ON ALL SCHEMAS IN DATABASE HRZN_DB TO ROLE HRZN_IT_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN DATABASE HRZN_DB TO ROLE HRZN_IT_ADMIN;
GRANT SELECT ON ALL VIEWS IN DATABASE HRZN_DB TO ROLE HRZN_IT_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_IT_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_IT_ADMIN;

/*=============================================================================
  ACCOUNT-LEVEL GOVERNANCE GRANTS (idempotent -- re-granting is a no-op)
=============================================================================*/

USE ROLE ACCOUNTADMIN;
GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE HRZN_DATA_ENGINEER;
GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE HRZN_DATA_ENGINEER;

GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE HRZN_DATA_GOVERNOR;
GRANT DATABASE ROLE SNOWFLAKE.OBJECT_VIEWER TO ROLE HRZN_DATA_GOVERNOR;
GRANT DATABASE ROLE SNOWFLAKE.USAGE_VIEWER TO ROLE HRZN_DATA_GOVERNOR;
GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE HRZN_DATA_GOVERNOR;
GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE HRZN_DATA_GOVERNOR;

GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE HRZN_IT_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.OBJECT_VIEWER TO ROLE HRZN_IT_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.USAGE_VIEWER TO ROLE HRZN_IT_ADMIN;
GRANT DATABASE ROLE SNOWFLAKE.DATA_METRIC_USER TO ROLE HRZN_IT_ADMIN;
GRANT EXECUTE DATA METRIC FUNCTION ON ACCOUNT TO ROLE HRZN_IT_ADMIN;

/*=============================================================================
  TABLES + DATA LOAD

  Loads from the public Snowflake quickstart S3 bucket (works in Snowsight).
  Source: Snowflake-Labs quickstart v2.0 by Ravi Kumar & Severin Gassauer

  FALLBACK: If S3 is unavailable, the CSVs are also bundled in this repo
  under data/. Upload them to the internal stage, then swap the COPY INTO:
    1.  snow stage copy data/CustomerDataRaw.csv @HRZN_DB.HRZN_SCH.DATA_STAGE --overwrite
        snow stage copy data/CustomerOrders.csv  @HRZN_DB.HRZN_SCH.DATA_STAGE --overwrite
    2.  Change the two COPY INTO statements below to load FROM @HRZN_DB.HRZN_SCH.DATA_STAGE/...
=============================================================================*/

USE ROLE HRZN_DATA_ENGINEER;
USE WAREHOUSE HRZN_WH;

-- FALLBACK ONLY: Uncomment to create an internal stage for loading bundled CSVs
-- when the S3 bucket is unavailable (see instructions in comment block above).
-- CREATE OR REPLACE STAGE HRZN_DB.HRZN_SCH.DATA_STAGE
--     FILE_FORMAT = (TYPE = 'CSV', SKIP_HEADER = 1);

CREATE OR REPLACE TABLE HRZN_DB.HRZN_SCH.CUSTOMER (
    ID FLOAT,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    STREET_ADDRESS VARCHAR,
    STATE VARCHAR,
    CITY VARCHAR,
    ZIP VARCHAR,
    PHONE_NUMBER VARCHAR,
    EMAIL VARCHAR,
    SSN VARCHAR,
    BIRTHDATE VARCHAR,
    JOB VARCHAR,
    CREDITCARD VARCHAR,
    COMPANY VARCHAR,
    OPTIN VARCHAR
);

CREATE OR REPLACE TABLE HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS (
    CUSTOMER_ID VARCHAR,
    ORDER_ID VARCHAR,
    ORDER_TS DATE,
    ORDER_CURRENCY VARCHAR,
    ORDER_AMOUNT FLOAT,
    ORDER_TAX FLOAT,
    ORDER_TOTAL FLOAT
);

COPY INTO HRZN_DB.HRZN_SCH.CUSTOMER
FROM s3://sfquickstarts/summit_2024_horizon_hol/CustomerDataRaw.csv
FILE_FORMAT = (TYPE = 'CSV', SKIP_HEADER = 1);

COPY INTO HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS
FROM s3://sfquickstarts/summit_2024_horizon_hol/CustomerOrders.csv
FILE_FORMAT = (TYPE = 'CSV', SKIP_HEADER = 1);

GRANT ALL ON TABLE HRZN_DB.HRZN_SCH.CUSTOMER TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT ON TABLE HRZN_DB.HRZN_SCH.CUSTOMER TO ROLE HRZN_DATA_USER;
GRANT SELECT ON TABLE HRZN_DB.HRZN_SCH.CUSTOMER TO ROLE HRZN_IT_ADMIN;

GRANT ALL ON TABLE HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT ON TABLE HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS TO ROLE HRZN_DATA_USER;
GRANT SELECT ON TABLE HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS TO ROLE HRZN_IT_ADMIN;

/*=============================================================================
  SALES_LEADS TABLE — Synthetic Data for Data Quality Demo
  
  3000 synthetic CRM leads with intentional quality issues that increase
  linearly by row number, so later rows are progressively dirtier:
    ~115 NULL emails         (every 26th row)
    ~103 blank phone numbers (every 29th row)
    ~71 duplicate emails     (every 41st row reuses a fixed email)
    ~63 invalid statuses     (every 47th row gets garbage values)
    ~37 out-of-range deals   (every 79th row: negative or > $1M)
  No external dependencies — generated entirely with GENERATOR + expressions.
=============================================================================*/

CREATE OR REPLACE TABLE HRZN_DB.HRZN_SCH.SALES_LEADS (
    LEAD_ID INT,
    LEAD_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    COMPANY VARCHAR,
    STATUS VARCHAR,
    DEAL_AMOUNT FLOAT,
    LEAD_SOURCE VARCHAR,
    CREATED_AT TIMESTAMP
) AS
WITH raw_data AS (
    SELECT
        ROW_NUMBER() OVER (ORDER BY SEQ4()) AS RN,
        SEQ4() AS S
    FROM TABLE(GENERATOR(ROWCOUNT => 3000))
)
SELECT
    RN AS LEAD_ID,

    'Lead_' || RN AS LEAD_NAME,

    CASE
        WHEN MOD(RN, 26) = 0 THEN NULL
        WHEN MOD(RN, 41) = 0 THEN 'duplicate_lead@example.com'
        ELSE 'lead_' || RN || '@example.com'
    END AS EMAIL,

    CASE
        WHEN MOD(RN, 29) = 0 THEN ''
        ELSE '555-' || LPAD(MOD(RN * 7, 10000)::VARCHAR, 4, '0')
    END AS PHONE,

    CASE MOD(RN, 8)
        WHEN 0 THEN 'Acme Corp'
        WHEN 1 THEN 'Globex Inc'
        WHEN 2 THEN 'Initech'
        WHEN 3 THEN 'Umbrella LLC'
        WHEN 4 THEN 'Stark Industries'
        WHEN 5 THEN 'Wayne Enterprises'
        WHEN 6 THEN 'Cyberdyne Systems'
        WHEN 7 THEN 'Soylent Corp'
    END AS COMPANY,

    CASE
        WHEN MOD(RN, 47) = 0 THEN
            CASE MOD(RN, 141)
                WHEN 0   THEN 'YOLO'
                WHEN 47  THEN 'idk'
                WHEN 94 THEN 'maybe_later'
            END
        ELSE
            CASE MOD(RN, 5)
                WHEN 0 THEN 'New'
                WHEN 1 THEN 'Contacted'
                WHEN 2 THEN 'Qualified'
                WHEN 3 THEN 'Proposal'
                WHEN 4 THEN 'Closed Won'
            END
    END AS STATUS,

    CASE
        WHEN MOD(RN, 79) = 0 THEN
            CASE WHEN MOD(RN, 158) = 0 THEN -5000.00
            ELSE 2500000.00
            END
        ELSE ROUND(1000 + UNIFORM(0::FLOAT, 99000::FLOAT, RANDOM()), 2)
    END AS DEAL_AMOUNT,

    CASE MOD(RN, 5)
        WHEN 0 THEN 'Website'
        WHEN 1 THEN 'Referral'
        WHEN 2 THEN 'Conference'
        WHEN 3 THEN 'Cold Call'
        WHEN 4 THEN 'Partner'
    END AS LEAD_SOURCE,

    DATEADD(minute, -RN * 15, CURRENT_TIMESTAMP()) AS CREATED_AT

FROM raw_data;

GRANT ALL ON TABLE HRZN_DB.HRZN_SCH.SALES_LEADS TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT ON TABLE HRZN_DB.HRZN_SCH.SALES_LEADS TO ROLE HRZN_DATA_USER;
GRANT SELECT ON TABLE HRZN_DB.HRZN_SCH.SALES_LEADS TO ROLE HRZN_IT_ADMIN;
GRANT ALL ON TABLE HRZN_DB.HRZN_SCH.SALES_LEADS TO ROLE HRZN_DATA_ENGINEER;

/*=============================================================================
  EMPLOYEES TABLE — Synthetic Data for Differential Privacy Demo
  
  2000 synthetic employees with numeric columns (salary, bonus, age).
  No external dependencies — generated entirely with GENERATOR + UNIFORM.
=============================================================================*/

CREATE OR REPLACE TABLE HRZN_DB.HRZN_SCH.EMPLOYEES (
    EMPLOYEE_ID INT,
    DEPARTMENT VARCHAR,
    SALARY FLOAT,
    BONUS FLOAT,
    AGE INT,
    YEARS_AT_COMPANY INT
) AS
SELECT
    ROW_NUMBER() OVER (ORDER BY SEQ4()) AS EMPLOYEE_ID,
    CASE MOD(SEQ4(), 6)
        WHEN 0 THEN 'Engineering'
        WHEN 1 THEN 'Sales'
        WHEN 2 THEN 'Marketing'
        WHEN 3 THEN 'Finance'
        WHEN 4 THEN 'Operations'
        WHEN 5 THEN 'Legal'
    END AS DEPARTMENT,
    ROUND(50000 + UNIFORM(0::FLOAT, 150000::FLOAT, RANDOM()), 2) AS SALARY,
    ROUND(UNIFORM(0::FLOAT, 25000::FLOAT, RANDOM()), 2) AS BONUS,
    22 + UNIFORM(0, 43, RANDOM()) AS AGE,
    UNIFORM(0, 25, RANDOM()) AS YEARS_AT_COMPANY
FROM TABLE(GENERATOR(ROWCOUNT => 2000));

GRANT ALL ON TABLE HRZN_DB.HRZN_SCH.EMPLOYEES TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT ON TABLE HRZN_DB.HRZN_SCH.EMPLOYEES TO ROLE HRZN_DATA_USER;
GRANT SELECT ON TABLE HRZN_DB.HRZN_SCH.EMPLOYEES TO ROLE HRZN_IT_ADMIN;

/*=============================================================================
  SUMMARY VIEW + POLICY / TAG / AI GOVERNANCE GRANTS
=============================================================================*/

USE ROLE HRZN_DATA_ENGINEER;
USE DATABASE HRZN_DB;
USE SCHEMA HRZN_DB.HRZN_SCH;

CREATE OR REPLACE VIEW HRZN_DB.HRZN_SCH.CUSTOMER_ORDER_SUMMARY AS
SELECT C.ID, C.FIRST_NAME, C.LAST_NAME,
       COUNT(CO.ORDER_ID) ORDERS_COUNT,
       SUM(CO.ORDER_TOTAL) ORDER_TOTAL
FROM HRZN_DB.HRZN_SCH.CUSTOMER C, HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS CO
WHERE C.ID = CO.CUSTOMER_ID
GROUP BY 1,2,3;

USE ROLE ACCOUNTADMIN;

GRANT APPLY TAG ON ACCOUNT TO ROLE HRZN_DATA_GOVERNOR;
GRANT APPLY MASKING POLICY ON ACCOUNT TO ROLE HRZN_DATA_GOVERNOR;
GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE HRZN_DATA_GOVERNOR;
GRANT APPLY AGGREGATION POLICY ON ACCOUNT TO ROLE HRZN_DATA_GOVERNOR;
GRANT APPLY PROJECTION POLICY ON ACCOUNT TO ROLE HRZN_DATA_GOVERNOR;
GRANT APPLY PRIVACY POLICY ON ACCOUNT TO ROLE HRZN_DATA_GOVERNOR;
GRANT CREATE PRIVACY POLICY ON SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_GOVERNOR;

GRANT DATABASE ROLE SNOWFLAKE.CLASSIFICATION_ADMIN TO ROLE HRZN_DATA_GOVERNOR;

GRANT CREATE SEMANTIC VIEW ON SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_GOVERNOR;
GRANT CREATE VIEW ON SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_GOVERNOR;
GRANT CREATE TABLE ON SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT ON TABLE HRZN_DB.HRZN_SCH.CUSTOMER TO ROLE HRZN_DATA_GOVERNOR;
GRANT SELECT ON TABLE HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS TO ROLE HRZN_DATA_GOVERNOR;
GRANT CREATE SCHEMA ON DATABASE HRZN_DB TO ROLE HRZN_DATA_GOVERNOR;

GRANT CREATE FUNCTION ON SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_GOVERNOR;
GRANT CREATE PROCEDURE ON SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_GOVERNOR;
GRANT USAGE ON SCHEMA HRZN_DB.CLASSIFIERS TO ROLE HRZN_DATA_GOVERNOR;
GRANT CREATE FUNCTION ON SCHEMA HRZN_DB.CLASSIFIERS TO ROLE HRZN_DATA_GOVERNOR;

GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_GOVERNOR;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_DATA_USER;
GRANT USAGE ON FUTURE FUNCTIONS IN SCHEMA HRZN_DB.HRZN_SCH TO ROLE HRZN_IT_ADMIN;

ALTER ACCOUNT SET CORTEX_MODELS_ALLOWLIST = 'All';
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'ANY_REGION';

/*=============================================================================
  DIFFERENTIAL PRIVACY — Privacy Policy + Domains on EMPLOYEES
  
  Entity-level privacy: each EMPLOYEE_ID is a protected entity.
  Governor sees exact results. All other roles get noisy aggregates
  with a weekly privacy budget.
=============================================================================*/

USE ROLE HRZN_DATA_GOVERNOR;
USE WAREHOUSE HRZN_WH;

CREATE OR REPLACE PRIVACY POLICY HRZN_DB.HRZN_SCH.EMPLOYEE_PRIVACY_POLICY
  AS () RETURNS PRIVACY_BUDGET ->
    CASE
      WHEN CURRENT_ROLE() IN ('HRZN_DATA_GOVERNOR', 'HRZN_DATA_ENGINEER', 'ACCOUNTADMIN')
        THEN NO_PRIVACY_POLICY()
      ELSE PRIVACY_BUDGET(BUDGET_NAME => 'analysts')
    END;

ALTER TABLE HRZN_DB.HRZN_SCH.EMPLOYEES
  ADD PRIVACY POLICY HRZN_DB.HRZN_SCH.EMPLOYEE_PRIVACY_POLICY
  ENTITY KEY (EMPLOYEE_ID);

USE ROLE HRZN_DATA_ENGINEER;

ALTER TABLE HRZN_DB.HRZN_SCH.EMPLOYEES
  MODIFY COLUMN SALARY SET PRIVACY DOMAIN BETWEEN (50000, 200000);
ALTER TABLE HRZN_DB.HRZN_SCH.EMPLOYEES
  MODIFY COLUMN BONUS SET PRIVACY DOMAIN BETWEEN (0, 25000);
ALTER TABLE HRZN_DB.HRZN_SCH.EMPLOYEES
  MODIFY COLUMN AGE SET PRIVACY DOMAIN BETWEEN (22, 65);
ALTER TABLE HRZN_DB.HRZN_SCH.EMPLOYEES
  MODIFY COLUMN YEARS_AT_COMPANY SET PRIVACY DOMAIN BETWEEN (0, 25);
ALTER TABLE HRZN_DB.HRZN_SCH.EMPLOYEES
  MODIFY COLUMN DEPARTMENT SET PRIVACY DOMAIN IN ('Engineering', 'Sales', 'Marketing', 'Finance', 'Operations', 'Legal');

SELECT 'Setup complete. HRZN_DB ready with CUSTOMER (' || 
       (SELECT COUNT(*) FROM HRZN_DB.HRZN_SCH.CUSTOMER) || 
       ' rows), CUSTOMER_ORDERS (' || 
       (SELECT COUNT(*) FROM HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS) || 
       ' rows), SALES_LEADS (' ||
       (SELECT COUNT(*) FROM HRZN_DB.HRZN_SCH.SALES_LEADS) ||
       ' rows), EMPLOYEES (' ||
       (SELECT COUNT(*) FROM HRZN_DB.HRZN_SCH.EMPLOYEES) ||
       ' rows, DP-protected).' AS status;
