/***************************************************************************************************
| H | O | R | I | Z | O | N |   | L | A | B | S |

Demo:         Horizon Catalog - Lab 2: Data Governor (Classification + Policies)
Version:      HLab v2.1 (Idempotent)
Gap:          + Compliance mapping comments (HIPAA/GDPR/PCI/CCPA)
***************************************************************************************************/

USE ROLE HRZN_DATA_USER;
USE WAREHOUSE HRZN_WH;
USE DATABASE HRZN_DB;
USE SCHEMA HRZN_SCH;

SELECT FIRST_NAME, LAST_NAME, STREET_ADDRESS, STATE, CITY, ZIP, PHONE_NUMBER, EMAIL, SSN, BIRTHDATE, CREDITCARD
FROM HRZN_DB.HRZN_SCH.CUSTOMER SAMPLE (100 ROWS);

/*=============================================================================
  AI CLASSIFICATION WITH TAG MAPPING
  
  Uses CLASSIFICATION_PROFILE with tag_map to:
  1. Auto-detect PII using AI classification
  2. Map detected PII to custom DATA_CLASSIFICATION tag
  3. Enable tag propagation to downstream tables
  
  [COMPLIANCE] Classification levels map to regulations:
    PII       → GDPR Art.4(1), HIPAA PHI, CCPA Personal Information
    RESTRICTED→ GDPR Art.9 (special categories), HIPAA limited dataset
    SENSITIVE → GDPR Art.6 (legitimate interest), PCI DSS Req 3
    INTERNAL  → SOX controls, internal-only business data
    PUBLIC    → No regulatory constraint
=============================================================================*/

USE ROLE HRZN_DATA_GOVERNOR;

CREATE SCHEMA IF NOT EXISTS HRZN_DB.TAG_SCHEMA;
USE SCHEMA HRZN_DB.TAG_SCHEMA;

CREATE OR REPLACE TAG HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION
    ALLOWED_VALUES 'PII', 'RESTRICTED', 'SENSITIVE', 'INTERNAL', 'PUBLIC'
    COMMENT = 'Enterprise data classification. GDPR/HIPAA/PCI/CCPA compliance mapping. Propagates to derived tables.'
    PROPAGATE = ON_DEPENDENCY_AND_DATA_MOVEMENT;

/*=============================================================================
  CLASSIFICATION PROFILE WITH TAG MAP
  
  [COMPLIANCE] tag_map semantic_categories → DATA_CLASSIFICATION level:
    EMAIL, SSN, CREDIT_CARD → PII   (GDPR: erasure required; HIPAA: PHI; PCI: encrypt)
    PHONE, DOB             → RESTRICTED (GDPR: Art.9; HIPAA: limited dataset)
    NAME, ADDRESS, CITY    → SENSITIVE  (GDPR: Art.6; PCI DSS Req 3)
    JOB, COMPANY           → INTERNAL   (SOX internal controls)
=============================================================================*/

USE ROLE SYSADMIN;

CREATE OR REPLACE SNOWFLAKE.DATA_PRIVACY.CLASSIFICATION_PROFILE
    HRZN_DB.HRZN_SCH.HRZN_STANDARD_CLASSIFICATION_PROFILE(
    {
      'minimum_object_age_for_classification_days': 0,
      'maximum_classification_validity_days': 90,
      'auto_tag': true,
      'classify_views': true,
      'tag_map': {
        'column_tag_map': [
          {
            'tag_name': 'HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION',
            'tag_value': 'PII',
            'semantic_categories': [
              'EMAIL',
              'US_SOCIAL_SECURITY_NUMBER',
              'NATIONAL_IDENTIFIER',
              'US_BANK_ACCOUNT_NUMBER',
              'CREDIT_CARD_NUMBER'
            ]
          },
          {
            'tag_name': 'HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION',
            'tag_value': 'RESTRICTED',
            'semantic_categories': [
              'PHONE_NUMBER',
              'DATE_OF_BIRTH'
            ]
          },
          {
            'tag_name': 'HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION',
            'tag_value': 'SENSITIVE',
            'semantic_categories': [
              'NAME',
              'STREET_ADDRESS',
              'CITY',
              'US_STATE',
              'ZIP_CODE'
            ]
          },
          {
            'tag_name': 'HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION',
            'tag_value': 'INTERNAL',
            'semantic_categories': [
              'JOB_TITLE',
              'OCCUPATION',
              'COMPANY'
            ]
          }
        ]
      }
    });

/*=============================================================================
  APPLY CLASSIFICATION PROFILE AND RUN AI CLASSIFICATION
=============================================================================*/

USE ROLE HRZN_DATA_GOVERNOR;

ALTER DATABASE HRZN_DB
    SET CLASSIFICATION_PROFILE = 'HRZN_DB.HRZN_SCH.HRZN_STANDARD_CLASSIFICATION_PROFILE';

CALL SYSTEM$CLASSIFY(
    'HRZN_DB.HRZN_SCH.CUSTOMER',
    'HRZN_DB.HRZN_SCH.HRZN_STANDARD_CLASSIFICATION_PROFILE'
);

SELECT TAG_DATABASE, TAG_SCHEMA, OBJECT_NAME, COLUMN_NAME, TAG_NAME, TAG_VALUE
FROM TABLE(
  HRZN_DB.INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS(
    'HRZN_DB.HRZN_SCH.CUSTOMER',
    'table'
))
ORDER BY TAG_NAME, COLUMN_NAME;

SELECT COLUMN_NAME, TAG_VALUE AS CLASSIFICATION_LEVEL
FROM TABLE(
    INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS(
        'HRZN_DB.HRZN_SCH.CUSTOMER', 'table'
    )
)
WHERE TAG_NAME = 'DATA_CLASSIFICATION'
ORDER BY
    CASE TAG_VALUE
        WHEN 'PII' THEN 1
        WHEN 'RESTRICTED' THEN 2
        WHEN 'SENSITIVE' THEN 3
        WHEN 'INTERNAL' THEN 4
        WHEN 'PUBLIC' THEN 5
    END, COLUMN_NAME;

/*=============================================================================
  CUSTOM CLASSIFICATION FOR CREDIT CARDS
=============================================================================*/

USE SCHEMA HRZN_DB.CLASSIFIERS;

CREATE OR REPLACE SNOWFLAKE.DATA_PRIVACY.CUSTOM_CLASSIFIER CREDITCARD();

CALL creditcard!add_regex('MC_PAYMENT_CARD','IDENTIFIER','^(?:5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)[0-9]{12}$');
CALL creditcard!add_regex('AMX_PAYMENT_CARD','IDENTIFIER','^3[4-7][0-9]{13}$');

SELECT creditcard!list();

SELECT CREDITCARD FROM HRZN_DB.HRZN_SCH.CUSTOMER WHERE CREDITCARD REGEXP '^3[4-7][0-9]{13}$' LIMIT 5;

CALL SYSTEM$CLASSIFY(
    'HRZN_DB.HRZN_SCH.CUSTOMER',
    {'custom_classifiers': ['HRZN_DB.CLASSIFIERS.CREDITCARD'], 'auto_tag': true}
);

SELECT SYSTEM$GET_TAG('snowflake.core.semantic_category','HRZN_DB.HRZN_SCH.CUSTOMER.CREDITCARD','column');

/*=============================================================================
  TAG-BASED MASKING POLICIES (Multi-Type)
  
  [COMPLIANCE] Masking satisfies:
    GDPR Art.25 — Data protection by design (pseudonymization)
    HIPAA §164.514 — De-identification standard
    PCI DSS Req 3.4 — Render PAN unreadable
    CCPA §1798.100 — Consumer right to access (role-based)
=============================================================================*/

USE ROLE HRZN_DATA_GOVERNOR;
USE SCHEMA HRZN_DB.TAG_SCHEMA;

CREATE OR REPLACE TABLE HRZN_DB.TAG_SCHEMA.CUSTOMER_CONSENT_MAP AS
SELECT DISTINCT ID AS CUSTOMER_ID, OPTIN FROM HRZN_DB.HRZN_SCH.CUSTOMER;

GRANT SELECT ON TABLE HRZN_DB.TAG_SCHEMA.CUSTOMER_CONSENT_MAP TO ROLE HRZN_DATA_USER;
GRANT SELECT ON TABLE HRZN_DB.TAG_SCHEMA.CUSTOMER_CONSENT_MAP TO ROLE HRZN_IT_ADMIN;

-- STRING MASKING POLICY [GDPR Art.25, HIPAA §164.514, PCI DSS Req 3.4]
CREATE OR REPLACE MASKING POLICY HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION_MASK_STRING
AS (VAL STRING) RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('HRZN_DATA_GOVERNOR', 'ACCOUNTADMIN') THEN VAL
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION') = 'PII'
    THEN '***PII-REDACTED***'
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION') = 'RESTRICTED'
    THEN CONCAT('***-', RIGHT(VAL, 4))
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION') = 'SENSITIVE'
    THEN CONCAT(LEFT(VAL, 1), REPEAT('*', LENGTH(VAL) - 1))
    ELSE VAL
END;

-- NUMBER MASKING POLICY [GDPR Art.25, PCI DSS Req 3.4]
CREATE OR REPLACE MASKING POLICY HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION_MASK_NUMBER
AS (VAL NUMBER) RETURNS NUMBER ->
CASE
    WHEN CURRENT_ROLE() IN ('HRZN_DATA_GOVERNOR', 'ACCOUNTADMIN') THEN VAL
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION') = 'PII' THEN NULL
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION') = 'RESTRICTED'
    THEN ROUND(VAL, -2)
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION') = 'SENSITIVE'
    THEN ABS(HASH(VAL))
    ELSE VAL
END;

-- DATE MASKING POLICY [HIPAA §164.514(b) — safe harbor date generalization]
CREATE OR REPLACE MASKING POLICY HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION_MASK_DATE
AS (VAL DATE) RETURNS DATE ->
CASE
    WHEN CURRENT_ROLE() IN ('HRZN_DATA_GOVERNOR', 'ACCOUNTADMIN') THEN VAL
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION') = 'PII' THEN NULL
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION') = 'RESTRICTED'
    THEN DATE_TRUNC('YEAR', VAL)
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION') = 'SENSITIVE'
    THEN DATE_TRUNC('MONTH', VAL)
    ELSE VAL
END;

-- TIMESTAMP MASKING POLICY [HIPAA §164.514(b)]
CREATE OR REPLACE MASKING POLICY HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION_MASK_TIMESTAMP
AS (VAL TIMESTAMP) RETURNS TIMESTAMP ->
CASE
    WHEN CURRENT_ROLE() IN ('HRZN_DATA_GOVERNOR', 'ACCOUNTADMIN') THEN VAL
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION') = 'PII' THEN NULL
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION') = 'RESTRICTED'
    THEN DATE_TRUNC('DAY', VAL)
    WHEN SYSTEM$GET_TAG_ON_CURRENT_COLUMN('HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION') = 'SENSITIVE'
    THEN DATE_TRUNC('MONTH', VAL)
    ELSE VAL
END;

-- ATTACH ALL POLICIES TO THE DATA_CLASSIFICATION TAG
ALTER TAG HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION SET MASKING POLICY HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION_MASK_STRING;
ALTER TAG HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION SET MASKING POLICY HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION_MASK_NUMBER;
ALTER TAG HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION SET MASKING POLICY HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION_MASK_DATE;
ALTER TAG HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION SET MASKING POLICY HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION_MASK_TIMESTAMP;

/*=============================================================================
  OPT-IN ROW ACCESS POLICY
  
  [COMPLIANCE] CCPA §1798.120 — Right to opt-out of data sale/sharing
              GDPR Art.7 — Conditions for consent
=============================================================================*/

CREATE OR REPLACE ROW ACCESS POLICY HRZN_DB.TAG_SCHEMA.CUSTOMER_OPTIN_POLICY
    AS (OPTIN_STATUS STRING) RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'HRZN_DATA_ENGINEER', 'HRZN_DATA_GOVERNOR', 'HRZN_IT_ADMIN')
        THEN TRUE
        WHEN CURRENT_ROLE() = 'HRZN_DATA_USER' AND OPTIN_STATUS = 'Y'
        THEN TRUE
        ELSE FALSE
    END;

ALTER TABLE HRZN_DB.HRZN_SCH.CUSTOMER
    ADD ROW ACCESS POLICY HRZN_DB.TAG_SCHEMA.CUSTOMER_OPTIN_POLICY ON (OPTIN);

/*=============================================================================
  TEST MASKING + OPT-IN WITH DIFFERENT ROLES
=============================================================================*/

USE ROLE HRZN_DATA_GOVERNOR;
SELECT ID, FIRST_NAME, EMAIL, SSN, PHONE_NUMBER, BIRTHDATE, COMPANY, OPTIN
FROM HRZN_DB.HRZN_SCH.CUSTOMER LIMIT 10;

SELECT COUNT(*) AS total_customers, SUM(CASE WHEN OPTIN = 'Y' THEN 1 ELSE 0 END) AS opted_in_customers
FROM HRZN_DB.HRZN_SCH.CUSTOMER;

USE ROLE HRZN_DATA_USER;
SELECT ID, FIRST_NAME, EMAIL, SSN, PHONE_NUMBER, BIRTHDATE, COMPANY, OPTIN
FROM HRZN_DB.HRZN_SCH.CUSTOMER LIMIT 10;

SELECT COUNT(*) AS visible_customers FROM HRZN_DB.HRZN_SCH.CUSTOMER;

/*=============================================================================
  TAG PROPAGATION TO DOWNSTREAM TABLES
  
  [COMPLIANCE] GDPR Art.5(2) — Accountability: governance must follow data lineage
=============================================================================*/

USE ROLE HRZN_DATA_GOVERNOR;

USE ROLE HRZN_DATA_ENGINEER;
CREATE TABLE HRZN_DB.HRZN_SCH.CUSTOMER_COPY AS SELECT * FROM HRZN_DB.HRZN_SCH.CUSTOMER;

USE ROLE HRZN_DATA_GOVERNOR;
SELECT COLUMN_NAME, TAG_VALUE AS CLASSIFICATION_LEVEL
FROM TABLE(
    INFORMATION_SCHEMA.TAG_REFERENCES_ALL_COLUMNS(
        'HRZN_DB.HRZN_SCH.CUSTOMER_COPY', 'table'
    )
)
WHERE TAG_NAME = 'DATA_CLASSIFICATION'
ORDER BY
    CASE TAG_VALUE
        WHEN 'PII' THEN 1 WHEN 'RESTRICTED' THEN 2
        WHEN 'SENSITIVE' THEN 3 WHEN 'INTERNAL' THEN 4
        WHEN 'PUBLIC' THEN 5
    END, COLUMN_NAME;

USE ROLE HRZN_DATA_USER;
SELECT * FROM HRZN_DB.HRZN_SCH.CUSTOMER_COPY LIMIT 5;

/*=============================================================================
  STATE-BASED ROW ACCESS POLICY
  
  [COMPLIANCE] GDPR Art.25 — Data protection by design (geographic restriction)
              HIPAA — Minimum necessary standard
=============================================================================*/

USE ROLE HRZN_DATA_GOVERNOR;

ALTER TABLE HRZN_DB.HRZN_SCH.CUSTOMER
    DROP ROW ACCESS POLICY HRZN_DB.TAG_SCHEMA.CUSTOMER_OPTIN_POLICY;

ALTER TABLE HRZN_DB.HRZN_SCH.CUSTOMER MODIFY COLUMN STATE UNSET TAG HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION;

USE ROLE HRZN_DATA_USER;
SELECT FIRST_NAME, STREET_ADDRESS, STATE, PHONE_NUMBER, EMAIL, JOB, COMPANY
FROM HRZN_DB.HRZN_SCH.CUSTOMER LIMIT 10;

USE ROLE HRZN_DATA_GOVERNOR;

SELECT * FROM HRZN_DB.TAG_SCHEMA.ROW_POLICY_MAP;

CREATE OR REPLACE ROW ACCESS POLICY HRZN_DB.TAG_SCHEMA.CUSTOMER_STATE_RESTRICTIONS
    AS (STATE STRING) RETURNS BOOLEAN ->
       CURRENT_ROLE() IN ('ACCOUNTADMIN','HRZN_DATA_ENGINEER','HRZN_DATA_GOVERNOR')
       OR EXISTS (
            SELECT rp.ROLE FROM HRZN_DB.TAG_SCHEMA.ROW_POLICY_MAP rp
            WHERE 1=1
                AND rp.ROLE = CURRENT_ROLE()
                AND rp.STATE_VISIBILITY = STATE
       )
COMMENT = 'Policy to limit rows by ROLE→STATE mapping. [COMPLIANCE] GDPR Art.25, HIPAA minimum necessary.';

ALTER TABLE HRZN_DB.HRZN_SCH.CUSTOMER
    ADD ROW ACCESS POLICY HRZN_DB.TAG_SCHEMA.CUSTOMER_STATE_RESTRICTIONS ON (STATE);

USE ROLE HRZN_DATA_USER;
SELECT FIRST_NAME, STREET_ADDRESS, STATE, PHONE_NUMBER, EMAIL, JOB, COMPANY
FROM HRZN_DB.HRZN_SCH.CUSTOMER;

/*=============================================================================
  AGGREGATION POLICIES
  
  [COMPLIANCE] GDPR Recital 26 — k-anonymity (MIN_GROUP_SIZE prevents re-identification)
              HIPAA §164.514(b) — Statistical de-identification
=============================================================================*/

USE ROLE HRZN_DATA_GOVERNOR;

CREATE OR REPLACE AGGREGATION POLICY HRZN_DB.TAG_SCHEMA.aggregation_policy
  AS () RETURNS AGGREGATION_CONSTRAINT ->
    CASE
      WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','HRZN_DATA_ENGINEER','HRZN_DATA_GOVERNOR')
      THEN NO_AGGREGATION_CONSTRAINT()
      ELSE AGGREGATION_CONSTRAINT(MIN_GROUP_SIZE => 100)
    END;

ALTER TABLE HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS
    SET AGGREGATION POLICY HRZN_DB.TAG_SCHEMA.aggregation_policy;

USE ROLE HRZN_DATA_USER;

SELECT ORDER_CURRENCY, SUM(ORDER_AMOUNT) FROM HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS GROUP BY ORDER_CURRENCY;

SELECT cl.state, cl.city, COUNT(oh.order_id) AS count_order, SUM(oh.order_amount) AS order_total
FROM HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS oh
JOIN HRZN_DB.HRZN_SCH.CUSTOMER cl ON oh.customer_id = cl.id
GROUP BY ALL ORDER BY order_total DESC;

/*=============================================================================
  PROJECTION POLICIES
  
  [COMPLIANCE] GDPR Art.5(1)(c) — Data minimisation
              PCI DSS Req 7 — Restrict access on need-to-know
=============================================================================*/

USE ROLE HRZN_DATA_GOVERNOR;
USE SCHEMA HRZN_DB.TAG_SCHEMA;

ALTER TABLE HRZN_DB.HRZN_SCH.CUSTOMER MODIFY COLUMN ZIP UNSET TAG HRZN_DB.TAG_SCHEMA.DATA_CLASSIFICATION;

CREATE OR REPLACE PROJECTION POLICY HRZN_DB.TAG_SCHEMA.projection_policy
  AS () RETURNS PROJECTION_CONSTRAINT ->
  CASE
    WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN','HRZN_DATA_ENGINEER', 'HRZN_DATA_GOVERNOR')
    THEN PROJECTION_CONSTRAINT(ALLOW => true)
    ELSE PROJECTION_CONSTRAINT(ALLOW => false)
  END;

ALTER TABLE HRZN_DB.HRZN_SCH.CUSTOMER MODIFY COLUMN ZIP
    SET PROJECTION POLICY HRZN_DB.TAG_SCHEMA.projection_policy;

USE ROLE HRZN_DATA_USER;

SELECT TOP 100 * EXCLUDE ZIP FROM HRZN_DB.HRZN_SCH.CUSTOMER;

SELECT * EXCLUDE ZIP FROM HRZN_DB.HRZN_SCH.CUSTOMER WHERE ZIP NOT IN ('97135','95357') LIMIT 10;

/*=============================================================================
  ROW ACCESS POLICY ON CUSTOMER_ORDERS — Cascading Governance
  
  Without this, CUSTOMER_ORDERS rows for filtered-out customers leak
  through semantic view joins as NULL dimensions (a "None" row showing
  aggregate revenue the user shouldn't see).
  
  This policy mirrors CUSTOMER_STATE_RESTRICTIONS: for each order,
  it checks whether the order's customer lives in a state the current
  role is allowed to see. If not, the order is hidden.
  
  [COMPLIANCE] GDPR Art.25 — Data protection by design
              HIPAA — Minimum necessary standard
=============================================================================*/

CREATE OR REPLACE ROW ACCESS POLICY HRZN_DB.TAG_SCHEMA.CUSTOMER_ORDERS_STATE_RESTRICTIONS
    AS (CUST_ID STRING) RETURNS BOOLEAN ->
       CURRENT_ROLE() IN ('ACCOUNTADMIN','HRZN_DATA_ENGINEER','HRZN_DATA_GOVERNOR')
       OR EXISTS (
            SELECT 1 FROM HRZN_DB.HRZN_SCH.CUSTOMER c
            JOIN HRZN_DB.TAG_SCHEMA.ROW_POLICY_MAP rp
              ON rp.ROLE = CURRENT_ROLE() AND rp.STATE_VISIBILITY = c.STATE
            WHERE c.ID = CUST_ID::FLOAT
       );

ALTER TABLE HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS
    ADD ROW ACCESS POLICY HRZN_DB.TAG_SCHEMA.CUSTOMER_ORDERS_STATE_RESTRICTIONS ON (CUSTOMER_ID);

/*=============================================================================
  CLEANUP FOR NEXT LABS
=============================================================================*/

USE ROLE HRZN_DATA_GOVERNOR;
ALTER TABLE HRZN_DB.HRZN_SCH.CUSTOMER_ORDERS UNSET AGGREGATION POLICY;
ALTER TABLE HRZN_DB.HRZN_SCH.CUSTOMER MODIFY COLUMN ZIP UNSET PROJECTION POLICY;
